import Network from './network';
export let registerUser = (data:{})=>Network.post('/register', data);
export let registerPhoneCode = (data:{})=>Network.get('/phone', data);
export let loginUser = (data:{})=>Network.post('/login', data);
export let addUser = (data:{})=>Network.post('/api/v1/users',data);
export let deleteUser = (data:{})=>Network.get(`/api/v1/delUsers`,data);
export let editUser = (data:{})=>Network.get(`/api/v1/editUsers`,data);
export let getUserList = (data:{}) =>Network.get('/api/v1/getUsers',data);
export let getRolesList = (data:{}) =>Network.get('/api/v1/getRoles',data);
export let addRole = (data:{})=>Network.post('/api/v1/roles',data);
export let deleteRole = (data:{})=>Network.get(`/api/v1/delRole`,data);
export let editRole = (data:{})=>Network.get(`/api/v1/editRole`,data);
export let addUserRole = (data:{})=>Network.post('/api/v1/userRoles',data);
export let delUserRole = (data:{})=>Network.get(`/api/v1/delUserRole`,data);
export let getRights = (data:{})=>Network.get(`/api/v1/getRights`,data);
export let addRights = (data:{})=>Network.post('/api/v1/rights',data);
export let delRights = (data:{})=>Network.get('/api/v1/delRights',data);
export let editRights = (data:{})=>Network.get(`/api/v1/editRights`,data);
export let getAllRights = ()=>Network.get(`/api/v1/getRights`);
export let addRoleRights = (data:{})=>Network.post('/api/v1/addRoleRight',data);
export let deleteRoleRights = (data:{})=>Network.post('/api/v1/delRoleRight',data);
